config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'login', to: 'home#show', as: 'login'
  get '/', to: 'home#show', as: 'home'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  root to: "home#show"
  get 'sessions/create'
  get 'sessions/destroy'
  get 'home/show'

  resources :job_levels
  resources :job_statuses
  resources :job_titles
  resources :company_info
  resources :business_units
  resources :employees
  resources :login
  resources :emergency_contacts
  resources :dependents
  resources :approvers
  resources :undertimes
  resources :leaves
  resources :overtimes
  resources :official_businesses
  resources :offsets
  resources :equipment_requests
  resources :managerviews
  resources :adminviews
  resources :userviews
  resources :special_days
  get "get_ot", to: "offsets#getot"

  post "employee_search", to: "employees#search"
  get "employee_search", to: "employees#search"

  post "add_sl", to: "employees#add_sick_leave_credit"
  post "add_vl", to: "employees#add_vacation_leave_credit"

  get "review_leaves", to: "managerviews#review_leaves", as: 'review_leaves'
  get "review_undertimes", to: "managerviews#review_undertimes", as: 'review_undertimes'
  get "review_overtimes", to: "managerviews#review_overtimes", as: 'review_overtimes'
  get "review_offsets", to: "managerviews#review_offsets", as: 'review_offsets'
  get "review_official_businesses", to: "managerviews#review_official_businesses", as: 'review_official_businesses'
  get "review_equipment_requests", to: "managerviews#review_equipment_requests", as: 'review_equipment_requests'

  get "admin_leaves", to: "adminviews#review_leaves", as: 'admin_leaves'
  get "admin_undertimes", to: "adminviews#review_undertimes", as: 'admin_undertimes'
  get "admin_overtimes", to: "adminviews#review_overtimes", as: 'admin_overtimes'
  get "admin_offsets", to: "adminviews#review_offsets", as: 'admin_offsets'
  get "admin_official_businesses", to: "adminviews#review_official_businesses", as: 'admin_official_businesses'
  get "admin_equipment_requests", to: "adminviews#review_equipment_requests", as: 'admin_equipment_requests'

  put "review_multiple_leaves", to: "leaves#review_multiple", as: 'review_multiple_leaves'
  put "review_multiple_undertimes", to: "undertimes#review_multiple", as: 'review_multiple_undertimes'
  put "review_multiple_overtimes", to: "overtimes#review_multiple", as: 'review_multiple_overtimes'
  put "review_multiple_offsets", to: "offsets#review_multiple", as: 'review_multiple_offsets'
  put "review_multiple_official_businesses", to: "official_businesses#review_multiple", as: 'review_multiple_official_businesses'
  put "review_multiple_equipment_requests", to: "equipment_requests#review_multiple", as: 'review_multiple_equipment_requests'

  get "profile/:id", to: "userviews#profile", as: 'profile'
  get "/view_subordinates/:id", to: "managerviews#view_subordinates", as: 'view_subordinates'

  put "email_leave/:id", to: "leaves#email", as: 'email_leave'
  put "email_undertime/:id", to: "undertimes#email", as: 'email_undertime'
  put "email_overtime/:id", to: "overtimes#email", as: 'email_overtime'
  put "email_ob/:id", to: "official_businesses#email", as: 'email_ob'
  put "email_offset/:id", to: "offsets#email", as: 'email_offset'

  post "manager/review/pending", to:"managerviews#sort_pending", as: 'manager_sort_pending'
  post "admin/review/pending", to:"adminviews#sort_pending", as: 'admin_sort_pending'

  get "/reports", to:"adminviews#reports", as: 'reports'
  get "/generate_report.csv", to: "adminviews#generate_report", as: 'download_report'
  post "/generate_report", to: "adminviews#generate_report", as: 'generate_report'

  get "reset_leaves", to: "adminviews#show_reset_leave_credits"
  post "reset_leave_credits", to: "adminviews#post_reset_leaves"

end

app/views/user_notifier/leave_approval_notification.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <p>Hi <%= @employee.firstlastname  %>,</p>

    <p>
    	Your leave application on <%= @leave.start_date.strftime("%b %d, %Y") %> to <%= @leave.end_date.strftime("%b %d, %Y") %> has been <%= @status %> by <%= @reviewed_by.firstlastname %>. <br>
			Click <a href="http://iems-beta.iripple.net<%= leafe_path(@leave) %>">here</a> to login to iEMS and check the details.
		</p> 

    <p>
    	Regards,<br> 
			iEMS Administrator
		</p>

  </body>
</html>

app/views/user_notifier/leave_notification.html.erb
<%= form_tag(email_leave_url(@leave), :method => :put) do %>

    <div class="row" style="margin-bottom: 20px">
      <div class="col-sm-6"><h2>Leave Details</h2></div>
    </div>

    <div class="row">
      <div class="col-sm-6" style="margin-bottom: 20px">
        <%= hidden_field_tag(:reviewed_by, @approver_id) %>
        <%= submit_tag "Approve", :class => "btn btn-default" %>
        <%= submit_tag "Deny", :class => "btn btn-default" %>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-12">

        <div class="row">
          <div class="col-sm-4">
            <div class="form-group">
              <label>Employee: </label>
              <%= Employee.find(@leave.employee_id).firstlastname %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-4">
            <div class="form-group">
              <label>Start Date: </label>
              <%= @leave.start_date.strftime("%b %d, %Y") %>
            </div>
          </div>
          <div class="col-sm-4">
            <div class="form-group">
              <label>End Date: </label>
              <%= @leave.end_date.strftime("%b %d, %Y") %>
            </div>
          </div>
          <div class="col-sm-4">
            <label>No.of Days: </label>
            <%= @leave.no_of_days %>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-4">
            <label>Leave Type</label>
            <%= @leave.leave_type %>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-12">
            <div class="form-group">
              <label for="comment">Reason: </label>
              <%= @leave.reason %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-12">
            <div class="form-group">
              <label for="comment">Remarks: </label>
              <%= @leave.remark %>
            </div>
          </div>
        </div>

      </div>
    </div>
<% end %>

app/views/user_notifier/ob_approval_notification.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <p>Hi <%= @employee.firstlastname  %>,</p>

    <p>
    	Your Official Business application on <%= @ob.start_date.strftime("%b %d, %Y %l:%M %p") %> to <%= @ob.end_date.strftime("%b %d, %Y %l:%M %p") %> has been <%= @status %> by <%= @reviewed_by.firstlastname %>. <br>
			Click <a href="http://iems-beta.iripple.net<%= official_business_path(@ob) %>">here</a> to login to iEMS and check the details.
		</p> 

    <p>
    	Regards,<br> 
			iEMS Administrator
		</p>

  </body>
</html>

app/views/user_notifier/ob_notification.html.erb
<%= form_tag(email_ob_url(@ob), :method => :put) do %>

    <div class="row" style="margin-bottom: 20px">
      <div class="col-sm-6"><h2>Official Business Details</h2></div>
    </div>

    <div class="row">
      <div class="col-sm-6" style="margin-bottom: 20px">
        <%= hidden_field_tag(:reviewed_by, @approver_id) %>
        <%= submit_tag "Approve", :class => "btn btn-default" %>
        <%= submit_tag "Deny", :class => "btn btn-default" %>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-12">
        <div class="row">
          <div class="col-sm-4">
            <div class="form-group">
              <label>Employee: </label>
              <%= Employee.find(@ob.employee_id).firstlastname %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-4">
            <div class="form-group">
              <label>Start Date: </label>
              <%= @ob.start_date.strftime("%b %d, %Y %l:%M %p")%>
            </div>
          </div>
          <div class="col-sm-4">
            <div class="form-group">
              <label>End Date: </label>
              <%= @ob.start_date.strftime("%b %d, %Y %l:%M %p") %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-12">
            <div class="form-group">
              <label for="comment">Purpose </label>
              <%= @ob.purpose %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-12">
            <div class="form-group">
              <label for="comment">Remarks: </label>
              <%= @ob.remark %>
            </div>
          </div>
        </div>

      </div>
    </div>
<% end %>

app/views/user_notifier/offset_approval_notification.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <p>Hi <%= @employee.firstlastname  %>,</p>

    <p>
    	Your Offset application on <%= @off.date.strftime("%b %d, %Y %l:%M %p") %> has been <%= @status %> by <%= @reviewed_by.firstlastname %>. <br>
			Click <a href="http://iems-beta.iripple.net<%= offset_path(@off) %>">here</a> to login to iEMS and check the details.
		</p> 

    <p>
    	Regards,<br> 
			iEMS Administrator
		</p>

  </body>
</html>

app/views/user_notifier/offset_notification.html.erb
<%= form_tag(email_offset_url(@off), :method => :put) do %>

    <div class="row" style="margin-bottom: 20px">
      <div class="col-sm-6"><h2>Offset Details</h2></div>
    </div>

    <div class="row">
      <div class="col-sm-6" style="margin-bottom: 20px">
        <%= hidden_field_tag(:reviewed_by, @approver_id) %>
        <%= submit_tag "Approve", :class => "btn btn-default" %>
        <%= submit_tag "Deny", :class => "btn btn-default" %>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-12">

        <div class="row">
          <div class="col-sm-4">
            <div class="form-group">
              <label>Employee: </label>
              <%= Employee.find(@off.employee_id).firstlastname %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-4">
            <div class="form-group">
              <label>Offset Date: </label>
              <%= @off.date.strftime("%b %d, %Y") %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-4">
            <div class="form-group">
              <label for="comment">Offset Type: </label>
              <%= @off.offset_type %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-12">
            <div class="form-group">
              <label for="comment">Purpose: </label>
              <%= @off.purpose %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-12">
            <div class="form-group">
              <label for="comment">Remarks: </label>
              <%= @off.remark %>
            </div>
          </div>
        </div>

      </div>
    </div>
<% end %>

app/views/user_notifier/overtime_approval_notification.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <p>Hi <%= @employee.firstlastname  %>,</p>

    <p>
    	Your Overtime application on <%= @ot.start_date.strftime("%b %d, %Y %l:%M %p") %> to <%= @ot.end_date.strftime("%b %d, %Y %l:%M %p") %> has been <%= @status %> by <%= @reviewed_by.firstlastname %>. <br>
			Click <a href="http://iems-beta.iripple.net<%= overtime_path(@ot) %>">here</a> to login to iEMS and check the details.
		</p> 

    <p>
    	Regards,<br> 
			iEMS Administrator
		</p>

  </body>
</html>

app/views/user_notifier/overtime_notification.html.erb
<%= form_tag(email_overtime_url(@ot), :method => :put) do %>

    <div class="row" style="margin-bottom: 20px">
      <div class="col-sm-6"><h2>Overtime Details</h2></div>
    </div>

    <div class="row">
      <div class="col-sm-6" style="margin-bottom: 20px">
        <%= hidden_field_tag(:reviewed_by, @approver_id) %>
        <%= submit_tag "Approve", :class => "btn btn-default" %>
        <%= submit_tag "Deny", :class => "btn btn-default" %>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-12">

        <div class="row">
          <div class="col-sm-4">
            <div class="form-group">
              <label>Employee: </label>
              <%= Employee.find(@ot.employee_id).firstlastname %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-4">
            <div class="form-group">
              <label>Start Date: </label>
              <%= @ot.start_date.strftime("%b %d, %Y %l:%M %p") %>
            </div>
          </div>
          <div class="col-sm-4">
            <div class="form-group">
              <label>End Date: </label>
              <%= @ot.end_date.strftime("%b %d, %Y %l:%M %p") %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-12">
            <div class="form-group">
              <label for="comment">No of Hours: </label>
              <%= @ot.no_of_hours %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-12">
            <div class="form-group">
              <label for="comment">Expected Output: </label>
              <%= @ot.expected_output %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-12">
            <div class="form-group">
              <label for="comment">Remarks: </label>
              <%= @ot.remark %>
            </div>
          </div>
        </div>

      </div>
    </div>
<% end %>

app/views/user_notifier/undertime_approval_notification.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <p>Hi <%= @employee.firstlastname  %>,</p>

    <p>
    	Your undertime application on <%= @undertime.date.strftime("%b %d, %Y %l:%M %p") %> has been <%= @status %> by <%= @reviewed_by.firstlastname %>. <br>
			Click <a href="http://iems-beta.iripple.net<%= undertime_path(@undertime) %>">here</a> to login to iEMS and check the details.
		</p> 

    <p>
    	Regards,<br> 
			iEMS Administrator
		</p>

  </body>
</html>

app/views/user_notifier/undertime_notification.html.erb
<%= form_tag(email_undertime_url(@undertime), :method => :put) do %>

    <div class="row" style="margin-bottom: 20px">
      <div class="col-sm-6"><h2>Undertime Details</h2></div>
    </div>

    <div class="row">
      <div class="col-sm-6" style="margin-bottom: 20px">
        <%= hidden_field_tag(:reviewed_by, @approver_id) %>
        <%= submit_tag "Approve", :class => "btn btn-default" %>
        <%= submit_tag "Deny", :class => "btn btn-default" %>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-12">

        <div class="row">
          <div class="col-sm-4">
            <div class="form-group">
              <label>Employee: </label>
              <%= Employee.find(@undertime.employee_id).firstlastname %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-4">
            <div class="form-group">
              <label>Undertime Date and Time: </label>
              <%= @undertime.date.strftime("%b %d %l:%M %p") %>
            </div>
          </div>
          <div class="col-sm-4">
            <label>Nature: </label>
            <%= @undertime.nature %>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-12">
            <div class="form-group">
              <label for="comment">Reason: </label>
              <%= @undertime.reason %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-12">
            <div class="form-group">
              <label for="comment">Remarks: </label>
              <%= @undertime.remark %>
            </div>
          </div>
        </div>

      </div>
    </div>
<% end %>