config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'login', to: 'home#show', as: 'login'
  get '/', to: 'home#show', as: 'home'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  root to: "home#show"
  get 'sessions/create'
  get 'sessions/destroy'
  get 'home/show'

  resources :job_levels
  resources :job_statuses
  resources :job_titles
  resources :company_info
  resources :business_units
  resources :employees
  resources :login
  resources :emergency_contacts
  resources :dependents
  resources :approvers
  resources :undertimes
  resources :leaves
  resources :overtimes
  resources :official_businesses
  resources :offsets
  resources :equipment_requests
  resources :managerviews
  resources :adminviews
  resources :userviews
  resources :special_days
  get "get_ot", to: "offsets#getot"

  post "employee_search", to: "employees#search"
  get "employee_search", to: "employees#search"

  post "add_sl", to: "employees#add_sick_leave_credit"
  post "add_vl", to: "employees#add_vacation_leave_credit"

  get "review_leaves", to: "managerviews#review_leaves", as: 'review_leaves'
  get "review_undertimes", to: "managerviews#review_undertimes", as: 'review_undertimes'
  get "review_overtimes", to: "managerviews#review_overtimes", as: 'review_overtimes'
  get "review_offsets", to: "managerviews#review_offsets", as: 'review_offsets'
  get "review_official_businesses", to: "managerviews#review_official_businesses", as: 'review_official_businesses'
  get "review_equipment_requests", to: "managerviews#review_equipment_requests", as: 'review_equipment_requests'

  get "admin_leaves", to: "adminviews#review_leaves", as: 'admin_leaves'
  get "admin_undertimes", to: "adminviews#review_undertimes", as: 'admin_undertimes'
  get "admin_overtimes", to: "adminviews#review_overtimes", as: 'admin_overtimes'
  get "admin_offsets", to: "adminviews#review_offsets", as: 'admin_offsets'
  get "admin_official_businesses", to: "adminviews#review_official_businesses", as: 'admin_official_businesses'
  get "admin_equipment_requests", to: "adminviews#review_equipment_requests", as: 'admin_equipment_requests'

  put "review_multiple_leaves", to: "leaves#review_multiple", as: 'review_multiple_leaves'
  put "review_multiple_undertimes", to: "undertimes#review_multiple", as: 'review_multiple_undertimes'
  put "review_multiple_overtimes", to: "overtimes#review_multiple", as: 'review_multiple_overtimes'
  put "review_multiple_offsets", to: "offsets#review_multiple", as: 'review_multiple_offsets'
  put "review_multiple_official_businesses", to: "official_businesses#review_multiple", as: 'review_multiple_official_businesses'
  put "review_multiple_equipment_requests", to: "equipment_requests#review_multiple", as: 'review_multiple_equipment_requests'

  get "profile/:id", to: "userviews#profile", as: 'profile'
  get "/view_subordinates/:id", to: "managerviews#view_subordinates", as: 'view_subordinates'

  put "email_leave/:id", to: "leaves#email", as: 'email_leave'
  put "email_undertime/:id", to: "undertimes#email", as: 'email_undertime'
  put "email_overtime/:id", to: "overtimes#email", as: 'email_overtime'
  put "email_ob/:id", to: "official_businesses#email", as: 'email_ob'
  put "email_offset/:id", to: "offsets#email", as: 'email_offset'

  post "manager/review/pending", to:"managerviews#sort_pending", as: 'manager_sort_pending'
  post "admin/review/pending", to:"adminviews#sort_pending", as: 'admin_sort_pending'

  get "/reports", to:"adminviews#reports", as: 'reports'
  get "/generate_report.csv", to: "adminviews#generate_report", as: 'download_report'
  post "/generate_report", to: "adminviews#generate_report", as: 'generate_report'

  get "reset_leaves", to: "adminviews#show_reset_leave_credits"
  post "reset_leave_credits", to: "adminviews#post_reset_leaves"

end

app/controllers/job_statuses_controller.rb
class JobStatusesController < ApplicationController
  layout 'admin'
  before_filter :check_session
  before_filter :admin_only, :except => [:edit, :update, :show, :create, :destroy]

  def admin_only
    unless current_user.is_admin == "Y"
      redirect_to userviews_path, :alert => "Access Denied"
    end
  end

  def index
    @job_statuses = JobStatus.where(status: 'A')
  end

  def new
    @job_status = JobStatus.new
  end

  def create
    @job_status = JobStatus.new(params[:job_status])
    @job_status.status = 'A'
    if @job_status.save
      redirect_to job_statuses_path#, :notice => "job_level saved"
    else
      render "new"
    end
  end

  def edit
    @job_status = JobStatus.find(params[:id])
  end

  def update
    @job_status = JobStatus.find(params[:id])
    if @job_status.update_attributes(params[:job_status])
      redirect_to job_statuses_path#, :notice => "Updated"
    else
      render "edit"
    end
  end

  def destroy
    @job_status = JobStatus.find(params[:id])
    @job_status.status = 'D'
    @job_status.save
    redirect_to job_statuses_path#, :notice => "Deleted"
  end
end

app/helpers/job_statuses_helper.rb
module JobStatusesHelper
end

app/views/job_statuses/edit.html.erb
<%= bootstrap_form_for @job_status do |f| %>

    <% if @job_status.errors.any? %>
        <div class="alert alert-danger">
          <strong>Error</strong>
          <ul><% @job_status.errors.full_messages.each do |m|%>
                <li><%= m %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="row" style="margin-bottom: 20px">
      <div class="col-sm-12"><h3>Edit Job Status</h3></div>
    </div>

    <div class="row">
      <div class="col-sm-12">
        <div class="row">
          <div class="col-sm-12">
            <%= f.text_field :name%>
          </div>
        </div>
        <div style="text-align:right">
          <button type="submit" class="btn btn-success">Save</button>
          <%= link_to "Back", job_statuses_path, :class => "btn btn-danger"%>
        </div>
      </div>
    </div>

<% end %>

app/views/job_statuses/index.html.erb
<!--breadcrumbs-->
  <!--breadcrumbs-->

<ul class="nav nav-pills nav-justified">
  <li><a href="/job_titles">Job Titles</a></li>
  <li><a href="/job_levels">Job Levels</a></li>
  <li class="active"><a href="/job_statuses">Job Statuses</a></li>
</ul>

<div class="row" style="margin-bottom: 20px">
  <div class="col-sm-6"><h3>Job Status</h3></div>
  <div class="col-sm-6" style="margin-top:15px; text-align: right"> <a href="job_statuses/new"><button type="button" class="btn btn-success"><b>+</b></button></a></div>
</div>

<div class="row">
  <div class="col-sm-12">
    <table class="table table-striped">
      <thead style="background-color: #0059bc; color:white">
      <tr>
        <th width="30%"data-field="id">ID</th>
        <th width="60%" data-field="name">Name</th>
        <th width="10%" colspan="2" data-field="edit"></th>
      </tr>
      </thead>
      <tbody>
      <% @job_statuses.each do |jb| %>
          <tr>
            <td><%= jb.id %></td>
            <td><%= jb.name %></td>
            <td><%= link_to image_tag("pencil.png", border: 0, width: 20, height: 20), edit_job_status_path(jb) %></td>
            <td><%= link_to image_tag("trash.png", border: 0, width: 20, height: 20), jb, :confirm => "Are you sure?", :method => :delete %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/job_statuses/new.html.erb
<%= bootstrap_form_for @job_status do |f| %>

    <% if @job_status.errors.any? %>
        <div class="alert alert-danger">
          <strong>Error</strong>
        <ul><% @job_status.errors.full_messages.each do |m|%>
              <li><%= m %></li>
          <% end %>
        </ul>
        </div>
    <% end %>

    <div class="row" style="margin-bottom: 20px">
      <div class="col-sm-12"><h3>Create Job Status</h3></div>
    </div>

    <div class="row">
      <div class="col-sm-12">
        <div class="row">
          <div class="col-sm-12">
            <%= f.text_field :name%>
          </div>
        </div>
        <div style="text-align:right">
          <button type="submit" class="btn btn-success">Save</button>
          <%= link_to "Back", job_statuses_path, :class => "btn btn-danger"%>
        </div>
      </div>
    </div>

<% end %>